### ISSUE TITLE
[BUG] License FAQ refers to AGPL

### ISSUE THREAD

**Issue by kakaroto** [kaleidos-ventures/taiga-resources#7]
Hi, I've just discovered Taiga, still looking around, but I noticed a discrepancy, where the repos seem to have switched from AGPL to MPL in April 15th, but the FAQ still talks about it being under the AGPL : 
https://resources.taiga.io/faqs/#license

Pretty much this file needs an update : https://github.com/kaleidos-ventures/taiga-resources/blob/main/content/faqs/license.md

P.S.: I would have loved to also see a blog post about the license change (why you did it, why you chose MPL, the challenges in doing that, etc.. as I'm looking at a possible license change on a project in one of the communities I'm in, and I thought it would be interesting to read your perspective).
Thanks!

**Comment by diacritica** [comment]
Hi @kakaroto  Thanks for spotting this, it might have slipped through our many changes.
It's now fixed! https://resources.taiga.io/faqs/#license and we added a short rationale at the end. Hope it helps!

**Comment by kakaroto** [comment]
No worries. It's hard to do a license change and not miss anything! :) Thanks for fixing it quickly!
