### ISSUE TITLE
[Q] Is it possible / is there a Guide to remove user-accounts from the platfrom not just members from boards

### ISSUE THREAD

**Issue by timmwille** [kaleidos-ventures/taiga-resources#8]
&gt; **READ THIS FIRST!**: We recently announced Taiga plans for the future and they greatly affect how we manage this repository and the current Taiga 6 release. Check it [here](https://blog.taiga.io/announcing_taiganext.html).chore: readme announce taiga-next

Thank you for reorganising the https://resources.taiga.io/faqs/ section it has many answers, though I could not find one that explains how an admin of the platform can remove user-accounts from the platform instead just members from individual boards... 

Thanks for the great work!

**Comment by ChriFo** [comment]
You have to use the "Django Admin" UI. Usage should be self-explanatory.

**Comment by Xaviju** [comment]
Hi there! 

Do you know that we created [Taiga Community](https://community.taiga.io/c/technical/8) for questions like yours? Please, check there; maybe another user has already asked something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.
